/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardOutreachRouteImport } from './routes/dashboard.outreach'
import { Route as DashboardOpportunityRouteImport } from './routes/dashboard.opportunity'
import { Route as DashboardMarketResearchRouteImport } from './routes/dashboard.market-research'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpportunityRoute = DashboardOpportunityRouteImport.update({
  id: '/opportunity',
  path: '/opportunity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketResearchRoute = DashboardMarketResearchRouteImport.update({
  id: '/market-research',
  path: '/market-research',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/market-research': typeof DashboardMarketResearchRoute
  '/dashboard/opportunity': typeof DashboardOpportunityRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/market-research': typeof DashboardMarketResearchRoute
  '/dashboard/opportunity': typeof DashboardOpportunityRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/market-research': typeof DashboardMarketResearchRoute
  '/dashboard/opportunity': typeof DashboardOpportunityRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/audit'
    | '/dashboard/competitors'
    | '/dashboard/leads'
    | '/dashboard/market-research'
    | '/dashboard/opportunity'
    | '/dashboard/outreach'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/audit'
    | '/dashboard/competitors'
    | '/dashboard/leads'
    | '/dashboard/market-research'
    | '/dashboard/opportunity'
    | '/dashboard/outreach'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/audit'
    | '/dashboard/competitors'
    | '/dashboard/leads'
    | '/dashboard/market-research'
    | '/dashboard/opportunity'
    | '/dashboard/outreach'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/outreach': {
      id: '/dashboard/outreach'
      path: '/outreach'
      fullPath: '/dashboard/outreach'
      preLoaderRoute: typeof DashboardOutreachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/opportunity': {
      id: '/dashboard/opportunity'
      path: '/opportunity'
      fullPath: '/dashboard/opportunity'
      preLoaderRoute: typeof DashboardOpportunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/market-research': {
      id: '/dashboard/market-research'
      path: '/market-research'
      fullPath: '/dashboard/market-research'
      preLoaderRoute: typeof DashboardMarketResearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardMarketResearchRoute: typeof DashboardMarketResearchRoute
  DashboardOpportunityRoute: typeof DashboardOpportunityRoute
  DashboardOutreachRoute: typeof DashboardOutreachRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardMarketResearchRoute: DashboardMarketResearchRoute,
  DashboardOpportunityRoute: DashboardOpportunityRoute,
  DashboardOutreachRoute: DashboardOutreachRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
